# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('comments', models.IntegerField(default=0)),
                ('label', models.CharField(blank=True, max_length=8)),
            ],
        ),
    ]
