# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-03 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='avatar_path',
            field=models.CharField(default='blog/images/defaultavata.png', max_length=200),
        ),
    ]
